// SPICK – Geo Matching
import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { corsHeaders } from "../_shared/email.ts";
const SUPA_URL="https://urjeijcncsyuletprydy.supabase.co";
const SUPA_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const SH={apikey:SUPA_KEY,"Authorization":"Bearer "+SUPA_KEY,"Content-Type":"application/json"};
async function geocode(a:string,c:string){try{const r=await fetch("https://nominatim.openstreetmap.org/search?q="+encodeURIComponent(a+", "+c+", Sweden")+"&format=json&limit=1&countrycodes=se",{headers:{"User-Agent":"Spick/1.0 hello@spick.se"}}).then(r=>r.json());if(r.length)return{lat:parseFloat(r[0].lat),lng:parseFloat(r[0].lon)};}catch(e){console.warn("geo: geocode failed",e);}return null;}
function haversine(lat1:number,lng1:number,lat2:number,lng2:number){const R=6371;
const dLat=(lat2-lat1)*Math.PI/180,dLng=(lng2-lng1)*Math.PI/180;const a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
async function findNearby(lat:number,lng:number,maxKm=20){const r=await fetch(SUPA_URL+"/rest/v1/cleaners?status=eq.aktiv&select=id,full_name,email,city,home_lat,home_lng,service_radius_km",{headers:SH}).then(r=>r.json());if(!Array.isArray(r))return[];return r.filter((c:Record<string,number>)=>c.home_lat&&c.home_lng).map((c:Record<string,number|string>)=>{const distance=haversine(lat,lng,Number(c.home_lat),Number(c.home_lng));return{...c,distance_km:Math.round(distance*10)/10};}).filter((c:Record<string,number>)=>c.distance_km<=Math.min(c.service_radius_km||10,maxKm)).sort((a:Record<string,number>,b:Record<string,number>)=>a.distance_km-b.distance_km);}
serve(async(req)=>{const CORS={...corsHeaders(req),"Access-Control-Allow-Methods":"POST, GET, OPTIONS"};if(req.method==="OPTIONS")return new Response(null,{headers:CORS});try{const{action,address,city,lat,lng,max_km=20,booking_id,cleaner_id,service_radius_km=10}=await req.json().catch(()=>({}));if(action==="geocode_booking"){const c=await geocode(address,city);if(!c)return new Response(JSON.stringify({error:"Kunde inte geocoda"}),{status:400,headers:{"Content-Type":"application/json",...CORS}});if(booking_id)await fetch(SUPA_URL+"/rest/v1/bookings?id=eq."+booking_id,{method:"PATCH",headers:{...SH,Prefer:"return=minimal"},body:JSON.stringify(c)});const cls=await findNearby(c.lat,c.lng);return new Response(JSON.stringify({ok:true,coords:c,cleaners:cls}),{headers:{"Content-Type":"application/json",...CORS}})}if(action==="find_cleaners"){const cls=await findNearby(lat,lng,max_km);return new Response(JSON.stringify({cleaners:cls}),{headers:{"Content-Type":"application/json",...CORS}})}if(action==="update_cleaner_location"){const c=await geocode(address,city);if(!c)return new Response(JSON.stringify({error:"Kunde inte geocoda"}),{status:400,headers:{"Content-Type":"application/json",...CORS}});await fetch(SUPA_URL+"/rest/v1/cleaners?id=eq."+cleaner_id,{method:"PATCH",headers:{...SH,Prefer:"return=minimal"},body:JSON.stringify({home_lat:c.lat,home_lng:c.lng,home_address:address,service_radius_km})});return new Response(JSON.stringify({ok:true,coords:c,service_radius_km}),{headers:{"Content-Type":"application/json",...CORS}})}return new Response(JSON.stringify({error:"Unknown action"}),{status:400,headers:{"Content-Type":"application/json",...CORS}})}catch(e){return new Response(JSON.stringify({error:(e as Error).message}),{status:500,headers:{"Content-Type":"application/json",...CORS}})}});