-- Lägg till saknade kolumner i bookings
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS message TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS pnr_hash TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cleaner_id UUID;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cancel_reason TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS rating_sent_at TIMESTAMPTZ;

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS referral_code TEXT;
